{
 "title": "NATS JetStream",
 "description": "NATS JetStream Dashboard",
 "tags": [
  "nats",
  "messaging"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_created,namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nats_varz_cpu{namespace=~\"$namespace\"},pod)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values(nats_stream_last_seq{namespace=~\"$namespace\",pod=~\"$pod\"}, stream_name)"
   },
   {
    "name": "consumer",
    "label": "Consumer",
    "query": "label_values(nats_consumer_num_pending{namespace=~\"$namespace\",pod=~\"$pod\"}, consumer_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{namespace=\"$namespace\", pod=~\"$pod\"})/sum(nats_varz_jetstream_config_max_storage{namespace=\"$namespace\", pod=~\"$pod\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{namespace=\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{namespace=\"$namespace\", pod=~\"$pod\"})/sum(nats_varz_jetstream_config_max_memory{namespace=\"$namespace\", pod=~\"$pod\"})"
    },
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{namespace=\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_connections{namespace=\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_config_max_storage{namespace=\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_config_max_memory{namespace=\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_server_total_consumers{namespace=\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "Stream metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Stream data size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_bytes{namespace=\"$namespace\", pod=~\"$pod\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_messages{namespace=\"$namespace\", pod=~\"$pod\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_stream_last_seq{namespace=\"$namespace\", pod=~\"$pod\",stream_name=~\"$stream\"}[$__rate_interval])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Messages per second (++/--)",
   "type": "timeseries",
   "description": "Messages added & processed per minute per consumer",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_num_pending{namespace=\"$namespace\", pod=~\"$pod\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])+rate(nats_consumer_delivered_consumer_seq{namespace=\"$namespace\", pod=~\"$pod\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} +"
    },
    {
     "expr": "- sum(rate(nats_consumer_delivered_consumer_seq{namespace=\"$namespace\", pod=~\"$pod\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} -"
    }
   ]
  },
  {
   "title": "Total delivered messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_delivered_consumer_seq{namespace=\"$namespace\", pod=~\"$pod\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Pending messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_pending{namespace=\"$namespace\", pod=~\"$pod\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Acks Pending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_ack_pending{namespace=\"$namespace\", pod=~\"$pod\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  }
 ]
}